# Generated by Django 2.1.2 on 2018-10-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogodki_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dogodek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=50)),
                ('datum', models.DateField()),
                ('rok_prijave', models.DateTimeField()),
                ('opis', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Dogodek',
                'verbose_name_plural': 'Dogodki',
            },
        ),
    ]
