# Generated by Django 2.1.2 on 2018-10-16 16:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dogodki_app', '0002_dogodek'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skupina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=50)),
                ('opis', models.TextField(null=True)),
                ('število_mest', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('dogodek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogodki_app.Dogodek')),
            ],
            options={
                'verbose_name': 'Skupina',
                'verbose_name_plural': 'Skupine',
            },
        ),
    ]
