# Generated by Django 2.1.5 on 2019-01-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogodki_app', '0004_auto_20181129_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='oddelek',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
