# Generated by Django 2.2.4 on 2021-08-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogodki_app', '0006_povabilo_email_poslan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fresh',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dogodek',
            name='opis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skupina',
            name='opis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
