# Generated by Django 2.2.4 on 2021-09-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dogodki_app', '0007_auto_20210809_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fresh',
            field=models.BooleanField(default=True),
        ),
    ]
