# Generated by Django 2.2.4 on 2022-01-11 10:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dogodki_app', '0008_auto_20210909_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogodek',
            name='cas_prijave',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
