# Generated by Django 2.2.4 on 2022-01-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogodki_app', '0009_dogodek_cas_prijave'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obvestilo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=60)),
                ('vsebina', models.TextField(blank=True, null=True)),
                ('email_poslan', models.BooleanField(default=False)),
                ('skupine', models.ManyToManyField(to='dogodki_app.Skupina')),
            ],
            options={
                'verbose_name': 'Obvestilo',
                'verbose_name_plural': 'Obvestila',
            },
        ),
    ]
