# Generated by Django 3.2.21 on 2023-09-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogodki_app', '0011_auto_20230921_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='oddelek',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
